#!/bin/bash -e
# create apt sources
# environment variables:
#   - required: CODENAME
#   - required: DISTRO
#   - optional: NONFREE

fatal() {
    echo "fatal: $@" 1>&2
    exit 1
}

[ -n "$CODENAME" ] || fatal "CODENAME is not set"
[ -n "$DISTRO" ] || fatal "DISTRO is not set"

SOURCES_LIST=/etc/apt/sources.list.d
mkdir -p $SOURCES_LIST

case "$DISTRO" in
    debian)
        SOURCES_TXT="
deb http://cdn.debian.net/debian $CODENAME main
deb http://cdn.debian.net/debian $CODENAME contrib
# deb http://cdn.debian.net/debian $CODENAME non-free"
        SECURITY_TXT="
deb http://security.debian.org/ $CODENAME/updates main
deb http://security.debian.org/ $CODENAME/updates contrib
# deb http://security.debian.org/ $CODENAME/updates non-free"
        ;;
    raspbian)
        SOURCES_TXT="
deb http://mirrordirector.raspbian.org/raspbian $CODENAME main
deb http://mirrordirector.raspbian.org/raspbian $CODENAME firmware
deb http://mirrordirector.raspbian.org/raspbian $CODENAME contrib
# deb http://mirrordirector.raspbian.org/raspbian $CODENAME non-free
deb http://archive.raspberrypi.org/debian $CODENAME main
        "
        SECURITY_TXT=""
        ;;
    *)
        fatal "DISTRO $DISTRO not known or unsupported"
        ;;
esac

cat >$SOURCES_LIST/sources.list<<EOF
deb http://archive.turnkeylinux.org/debian $CODENAME main
$SOURCES_TXT
EOF

cat >$SOURCES_LIST/security.sources.list<<EOF
deb http://archive.turnkeylinux.org/debian $CODENAME-security main
$SECURITY_TXT
EOF

if [ "$NONFREE" ]; then
    sed -i "/non-free/ s/# //" $SOURCES_LIST/sources.list
    sed -i "/non-free/ s/# //" $SOURCES_LIST/security.sources.list
fi

