#!/bin/bash -e
# Regenerate TLS (aka SSL) keys and certificates

[ -n "$_TURNKEY_INIT" ] && exit 0

[[ -e $INITHOOKS_CONF ]] && . $INITHOOKS_CONF

fatal() {
    echo "fatal: $@" 1>&2
    exit 1
}

which openssl >/dev/null || fatal "openssl is not installed"

# A minimum DH group of 1024 bits is required to combat FREAK and Logjam, but
# 2048 (or higher) is recommended. However, generating it takes quite a while,
# especially at boot time (when entropy may be low). So if running live, or the
# server only has a 1 CPU, a 1024 bit Diffie-Hellman is generated, otherwise
# load from inithooks.conf; DH_BITS, with a default fallback to 2048.

cpus=$(grep -c ^processor /proc/cpuinfo)
if grep -qs 'boot=live' /proc/cmdline; then
    DH_BITS=1024
# if preseeds file exists, but DH_BITS not set, assuming it's a Hub server
elif [[ -e $INITHOOKS_CONF ]] && [[ -z "$DH_BITS" ]]; then
    if [[ $cpus -lt 2 ]]; then
        DH_BITS=1024
    else
        DH_BITS=2048
    fi
fi

$INITHOOKS_PATH/bin/dhparams.py --bits "$DH_BITS"
#openssl dhparam -out /etc/ssl/private/dhparams.pem $DH_BITS
#chmod 400 /etc/ssl/private/dhparams.pem

echo "Regenerating SSL keys and certificates..."

# Use turnkey-make-ssl-cert to generate default server cert
/usr/local/bin/turnkey-make-ssl-cert --default --force-overwrite

# Restart relevant installed services
which nginx >/dev/null && service nginx restart
which tomcat7 >/dev/null && service tomcat7 restart 
which apache2 >/dev/null && service apache2 restart
which lighttpd >/dev/null && service lighttpd restart
which stunnel4 >/dev/null && service stunnel4 restart

# final tidy up
update-ca-certificates

